[target.x86_64-unknown-linux-musl]
pre-build = [
    "DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y protobuf-compiler cmake clang"
]

[target.aarch64-unknown-linux-musl]
pre-build = [
    "DEBIAN_FRONTEND=noninteractive apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y protobuf-compiler cmake clang"
]
