[env]
KUIPER_CA_ORG = "KuiperOrg"
GITHUB_APP_ID = "12345"
GITHUB_PRIVATE_KEY = "--- key here ---"

[tasks.precommit]
run = [
    "cargo clippy --all-targets -- -D clippy::uninlined_format_args",
    "cargo fmt",
    "cargo test --all"
]

[tasks.clippy-fix]
run = "cargo clippy --all-targets --fix --allow-dirty -- -D clippy::uninlined_format_args"
